### ISSUE TITLE
Additional modules: Reference preparation

### ISSUE THREAD

**Issue by tilschaef** [UMCUGenetics/RNASeq-NF#7]
Implement sub-workflow to prepare all necessary files to deploy a new reference genome/transcriptome. 

This should include at least the following modules for now.

- Star genomeGenerate
- GTF /GFFto BED12 conversion (RSeQC)

**Comment by mroosmalen** [comment]
How do you create the scatter_interval_list file: Homo_sapiens.GRCh37.GATK.illumina.chromosomes.interval_list? Or how does it look like?

**Comment by tilschaef** [comment]
Implemented. Reference files, such as star and salmon index, will be automatically prepared if not provided by the user. The only requirements are fasta/gtf inputs.
