### ISSUE TITLE
FastQC report only included in MultiQC when TrimGalore step enabled

### ISSUE THREAD

**Issue by ffmmulder** [UMCUGenetics/RNASeq-NF#73]
Disabling TrimGalore in the pipeline will still generate FastQC report for the raw data, however results are not included in final MultiQC report. When enabling TrimGalore the FastQC report for the trimmed data IS included.

*Fix
Add line
"fastqc_logs = FastQC.out.fastqc_report "

After FastQC(fastq_files) in first if statement in the pre_processing.nf workflow...

**Comment by tilschaef** [comment]
That's indeed the case, thanks for sharing. 

Could you submit a pull request?

**Comment by tilschaef** [comment]
Fixed in 98158acd87723689f475449a3925239b41d705a
